### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' 

### ISSUE THREAD

**Issue by dappstore123** [ethereumclassic/explorer#308]
TypeError: Cannot read property 'toLowerCase' of undefined
    at getAddr (/home/ubuntu/e2/routes/index.js:41:30)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/e2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/ubuntu/e2/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/e2/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/ubuntu/e2/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/e2/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at /home/ubuntu/e2/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/ubuntu/e2/node_modules/raw-body/index.js:224:16)
TypeError: Cannot read property 'toLowerCase' of undefined
    at getAddr (/home/ubuntu/e2/routes/index.js:41:30)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/e2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/ubuntu/e2/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/e2/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/ubuntu/e2/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/ubuntu/e2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/e2/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/e2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/e2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/e2/node_modules/express/lib/router/index.js:275:10)
    at /home/ubuntu/e2/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/ubuntu/e2/node_modules/raw-body/index.js:224:16)

/home/ubuntu/e2/node_modules/solc/soljson.js:28

**Comment by btenterprise2020** [comment]
That is the normal error, you need to install mongodb and populate the DB before using it!
